In [10]:
import numpy as np

from strat import MacdCrossAndRSIOver

from quantfreedom.enums import *
from quantfreedom.helper_funcs import dl_ex_candles

np.set_printoptions(formatter={"float_kind": "{:0.2f}".format})


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
candles = dl_ex_candles(
    exchange="mufex",
    symbol="BTCUSDT",
    timeframe="5m",
    candles_to_dl=1000,
)

In [21]:
long_strat = MacdCrossAndRSIOver(
    long_short="long",
    rsi_length=np.array([14]),
    rsi_is_below=np.arange(35, 61, 5),
    ema_length=np.arange(100, 501, 100),
    fast_length=np.arange(10, 61, 10),
    macd_below=np.arange(0, 51, 25),
    signal_smoothing=np.arange(5, 16, 5),
    slow_length=np.arange(30, 121, 30)
)

long_strat.set_entries_exits_array(
    candles=candles,
    ind_set_index=2,
)
long_strat.plot_signals(candles=candles)

[[0.00 0.00 0.00 ... 0.00 0.00 0.00]
 [35.00 35.00 35.00 ... 60.00 60.00 60.00]
 [14.00 14.00 14.00 ... 14.00 14.00 14.00]
 ...
 [0.00 0.00 0.00 ... 50.00 50.00 50.00]
 [5.00 5.00 5.00 ... 15.00 15.00 15.00]
 [30.00 60.00 90.00 ... 60.00 90.00 120.00]]
